[workspace]
authors = ["Wolf Vollprecht <w.vollprecht@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "build-recipe"
platforms = ["osx-arm64"]
preview = ["pixi-build"]
version = "0.1.0"

[tasks]

[dependencies]
bzip2 = { path = "./recipes/bzip2" }
python = "3.12.*"

# [build-variants.options]
# inherit-from = "conda-forge"
# zip_keys = [["python", "numpy"],]

# [build-variants.keys]
# python = ["3.12", "3.11"]
# numpy = ["1.21", "1.20"]
# c_compiler = ["gcc"]
