name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
    types:
      - labeled
      - synchronize
      - opened

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

env:
  CICD_INTERMEDIATES_DIR: "_cicd-intermediates"
  XDG_CACHE_HOME: ${{ github.workspace }}/.cache
  PYTEST_ADDOPTS: "--color=yes"

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Set up pixi
        uses: prefix-dev/setup-pixi@main
        with:
          environments: lint
      - name: pre-commit
        run: pixi run pre-commit-run --color=always --show-diff-on-failure

  #
  # Run integration tests on important platforms
  #

  # test-pytest-windows-x86_64:
  #   timeout-minutes: 10
  #   name: Pytest | windows x86_64
  #   runs-on: windows-latest
  #   needs: build-binary-windows-x86_64
  #   env:
  #     TARGET_RELEASE: "target/pixi/release"
  #   steps:
  #     - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
  #     - name: Create Dev Drive
  #       run: ${{ github.workspace }}/.github/workflows/setup-dev-drive.ps1
  #     - name: Copy Git Repo to Dev Drive
  #       run: |
  #         Copy-Item -Path "${{ github.workspace }}" -Destination "${{ env.PIXI_WORKSPACE }}" -Recurse
  #         echo "${{ env.PIXI_WORKSPACE }}/${{ env.TARGET_RELEASE }}" | Out-File -Append -Encoding utf8 -FilePath $env:GITHUB_PATH
  #     - name: Download binary from build
  #       uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4
  #       with:
  #         name: pixi-windows-x86_64-${{ github.sha }}
  #         path: ${{ env.PIXI_WORKSPACE }}/${{ env.TARGET_RELEASE }}
  #     - name: Verify pixi installation
  #       working-directory: ${{ env.PIXI_WORKSPACE }}
  #       run: pixi info

  #     - name: Run pytests
  #       working-directory: ${{ env.PIXI_WORKSPACE }}
  #       run: pixi run --locked test-integration-ci

  # test-pytest-macos-aarch64:
  #   timeout-minutes: 10
  #   name: Pytest | macos aarch64
  #   runs-on: macos-14
  #   needs: build-binary-macos-aarch64
  #   env:
  #     TARGET_RELEASE: "${{ github.workspace }}/target/pixi/release"
  #   steps:
  #     - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
  #     - name: Download binary from build
  #       uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4
  #       with:
  #         name: pixi-macos-aarch64-${{ github.sha }}
  #         path: ${{ env.TARGET_RELEASE }}
  #     - name: Setup unix binary, add to github path
  #       run: |
  #         chmod a+x ${{ env.TARGET_RELEASE }}/pixi
  #         echo "${{ env.TARGET_RELEASE }}" >> $GITHUB_PATH
  #     - name: Verify pixi installation
  #       run: pixi info

  #     - name: Run integration tests
  #       run: pixi run --locked test-integration-ci

  test:
    timeout-minutes: 10
    name: Build | ${{ matrix.os }} ${{ matrix.arch }}
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: linux
            arch: x86_64
            runner: 8core_ubuntu_latest_runner
          - os: windows
            arch: x86_64
            runner: windows-latest
          - os: macos
            arch: aarch64
            runner: macos-14
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Create Dev Drive (Windows)
        if: matrix.os == 'windows'
        # This script also sets PIXI_WORKSPACE
        run: ${{ github.workspace }}/.github/workflows/setup-dev-drive.ps1

      - name: Set PIXI_WORKSPACE (Unix)
        if: matrix.os != 'windows'
        run: echo "PIXI_WORKSPACE=${{ github.workspace }}" >> $GITHUB_ENV

      - name: Copy Git Repo to Dev Drive (Windows)
        if: matrix.os == 'windows'
        run: |
          Copy-Item -Path "${{ github.workspace }}" -Destination "${{ env.PIXI_WORKSPACE }}" -Recurse
          echo "${{ env.PIXI_WORKSPACE }}/target/pixi/release" | Out-File -Append -Encoding utf8 -FilePath $env:GITHUB_PATH
        env:
          TARGET_RELEASE: "target/pixi/release"

      - name: Set up pixi
        uses: prefix-dev/setup-pixi@main
        with:
          manifest-path: ${{ env.PIXI_WORKSPACE }}/pixi.toml
          cache: true
          cache-write: ${{ github.event_name == 'push' && github.ref_name == 'main' }}

      - name: Download artifacts
        working-directory: ${{ env.PIXI_WORKSPACE }}
        run: |
          pixi run download-artifacts pixi
          pixi run download-artifacts pixi-build-backends
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup unix binary permissions (Unix)
        if: matrix.os != 'windows'
        working-directory: ${{ env.PIXI_WORKSPACE }}
        run: |
          chmod a+x ${{ env.WORKSPACE_DIR }}/artifacts/pixi

      - name: Run integration tests
        run: pixi run --locked test
        working-directory: ${{ env.PIXI_WORKSPACE }}
        env:
          PIXI_BIN_DIR: ${{ env.PIXI_WORKSPACE }}/artifacts
          BUILD_BACKENDS_BIN_DIR: ${{ env.PIXI_WORKSPACE }}/artifacts
